version: "3"

services:
    db:
        environment:
            MYSQL_DATABASE: fischbot
            MYSQL_USER: fischbot
            MYSQL_PASSWORD: fischbot
            MYSQL_ROOT_PASSWORD: fischbotRoot
    app:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        environment:
            NODE_ENV: development
            DB__PORT: 3306
            DB__NAME: fischbot
            DB__USER: fischbot
            DB__PASSWORD: fischbot
            APP__HOST: fischbot.ngrok.io
            APP__PORT: 3000
            REDIS__SECRET: devSecretIAmVerySecureNot
            REDIS__PORT: 6379
        ports: 
            - 3000:3000
        volumes: 
            - "./:/usr/src/app"
    
    adminer:
        image: adminer
        ports:
            - 8080:8080
        expose: 
            - 8080
        environment: 
            ADMINER_DESIGN: pepa-linha
