version: "3"

services:
    db:
        environment: 
            MYSQL_DATABASE: ${DB__NAME}
            MYSQL_USER: ${DB__USER}
            MYSQL_PASSWORD: ${DB__PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB__ROOT_PASSWORD}
            
    app:
        build:
            dockerfile: Dockerfile.dev
        environment:
            NODE_ENV: dev
            
        volumes: 
            - "./:/usr/src/app"

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: db
        depends_on: 
            - db