version: "3"

services:
    db:
        environment: 
            MYSQL_DATABASE: ${DB__NAME}
            MYSQL_USER: ${DB__USER}
            MYSQL_PASSWORD: ${DB__PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB__ROOT_PASSWORD}

    app:
        build:
            dockerfile: Dockerfile.prod
        environment:
            NODE_ENV: prod